# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Hbbtstar's Spot
tagline:             'Tech tidbits'
description:         'Sundry tech posts and stories'
url:                 https://hbbtstar.github.io
baseurl:             ''
paginate:            5
gems: [jekyll-sitemap, jekyll-paginate, jekyll-feed]
# About/contact
author:
  name:              Alexander Lourenco
  url:               https://hbbtstar.github.io
  email:             hbbtstar@gmail.com

# Custom vars
version:             1.0.0
